### ISSUE TITLE
JSON keys which start with digitals should be convert to string value

### ISSUE THREAD

**Issue by unlsycn** [sempruijs/json2nix#18]
example:
```json
{ "1": [], "2": [] }
```

current result is
```nix
{
  1 = [];
  2 = [];
}
```
that is illegal.

**Comment by sempruijs** [comment]
Ah I see, thanks for reporting! I will fix this

**Comment by sempruijs** [comment]
hi @unlsycn, I think it's fixed now. It works on my machine. Could you check on yours?

**Comment by unlsycn** [comment]
> hi @unlsycn, I think it's fixed now. It works on my machine. Could you check on yours?

Sorry for my late reply, the result on my machine is still the same, which is incorrect.

**Comment by sempruijs** [comment]
Hi @unlsycn 
Found the other error :) Even updated the readme with your example.
Feel free to test and take your time :D

**Comment by unlsycn** [comment]
> Hi @unlsycn Found the other error :) Even updated the readme with your example. Feel free to test and take your time :D

Sorry, my example may be a bit confusing. See https://github.com/sempruijs/json2nix/commit/533aa59cd913301fc5201c7786b729e5ab526ecd#r150729562
and try this:
```json
{ "1": [], "2foo": [] }
```

**Comment by unlsycn** [comment]
> > Hi [@unlsycn](https://github.com/unlsycn) Found the other error :) Even updated the readme with your example. Feel free to test and take your time :D
> 
> Sorry, my example may be a bit confusing. See [533aa59#r150729562](https://github.com/sempruijs/json2nix/commit/533aa59cd913301fc5201c7786b729e5ab526ecd#r150729562) and try this:
> 
> { "1": [], "2foo": [] }

ping
